webtalk_init -webtalk_dir C:\\workspace\\Arty_DigiLED\\Arty_DigiLED.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Dec 10 20:45:43 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "bklngep4t1c8aocpfhq8rke6ou" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.4_5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1449808882377" -context "sdk\\\\bsp/1449808882377"
webtalk_add_data -client sdk -key hwid -value "1449612122678" -context "sdk\\\\bsp/1449808882377"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1449808882377"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1449808882377"
webtalk_add_data -client sdk -key uid -value "1449809014624" -context "sdk\\\\bsp/1449809014624"
webtalk_add_data -client sdk -key hwid -value "1449612122678" -context "sdk\\\\bsp/1449809014624"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1449809014624"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1449809014624"
webtalk_add_data -client sdk -key uid -value "1449809015660" -context "sdk\\\\application/1449809015660"
webtalk_add_data -client sdk -key hwid -value "1449612122678" -context "sdk\\\\application/1449809015660"
webtalk_add_data -client sdk -key bspid -value "1449809014624" -context "sdk\\\\application/1449809015660"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1449809015660"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1449809015660"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1449809015660"
webtalk_transmit -clientid 3297262270 -regid "" -xml C:\\workspace\\Arty_DigiLED\\Arty_DigiLED.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\workspace\\Arty_DigiLED\\Arty_DigiLED.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\workspace\\Arty_DigiLED\\Arty_DigiLED.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
